name: Build Python Package
    
on:
  push:
  pull_request:
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_dev.txt
        pip install setuptools wheel twine
    - name: Run tests
      run: |
        flake8 pyscihub tests
        python setup.py test
        tox
    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel
